### ISSUE TITLE
Local authroize call gets rejected because of content type "application/x-www-form-urlencoded"

### ISSUE THREAD

**Issue by ttonyh** [nuxt-alt/auth#104]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v21.4.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.1
- Builder:          -
- User Config:      devtools, devServer, plugins, modules
- Runtime Modules:  ~/modules/dynamic-config.ts, @nuxt-alt/auth@3.1.4, @nuxtjs/robots@3.0.0, @nuxtjs/color-mode@3.3.2, @vee-validate/nuxt@4.12.4
- Build Modules:    -
------------------------------

### Nuxt Config

N/A

### Reproduction

Call the loginWith method on the strategy.

### Describe the bug

Upgrading from  @nuxt-alt/auth `3.0.5` to `3.1.4` causes the auth to call a local method (in Nuxt) that calls the endpoint, which returns a 415 error of `Unsupported media type application/x-www-form-urlencoded;charset=UTF-8 in request`. Digging though the auth source, I noticed that there's a config named `useForms` that changes the content-type header. I tried to apply this option, both in the root of the config and inside of the strategy and I still get the same result.

**Comment by Denoder** [comment]
try using `nuxt-alt/auth@beta`

**Comment by Denoder** [comment]
okay update the the beta tag again and try again. I've decoupled the request from forwarding previous headers.

**Comment by Denoder** [comment]
Use the http module options and enable debugging and post the output.
