### ISSUE TITLE
useAuth() gives trouble when executing loginWith()

### ISSUE THREAD

**Issue by azmatzuberi** [nuxt-alt/auth#105]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules, auth
- Runtime Modules:  @nuxt-alt/auth@3.1.5
- Build Modules:    -

### Nuxt Config
```ts
devtools: { enabled: false },
modules: ['@nuxt-alt/auth'],
auth: {
    globalMiddleware: true,
    enableMiddleware: true,
    redirect: {
        login: '/sign-in',
        logout: '/',
        callback: '/',
        home: '/',
    },
    strategies: {
        local: {
            scheme: 'refresh',
            token: {
                property: 'access_token',
                maxAge: 1800,
                global: true,
                type: '',
                max: 60 * 10,
                name: 'api-x-auth-token',
            },
            refreshToken: {
                property: 'refresh_token',
                data: 'refresh_token',
                maxAge: 60 * 60 * 24 * 7,
            },
            user: {
                property: 'user',
                // data: 'user'
                autoFetch: false,
            },
            endpoints: {
                login: {
                    url: `http://localhost:4500/api/users/sign-in`,
                    method: 'post',
                },
                logout: {
                    url: `http://localhost:4500/api/users/logout`,
                    method: 'post',
                },
                refresh: {
                    url: `http://localhost:4500/api/users/refresh`,
                    method: 'post',
                },
                user: {
                    url: `http://localhost:4500/api/users/user-info`,
                    method: 'get',
                },
            },
            // autoLogout: false
        },
    },
},
```
### Reproduction

Add useAuth().loginWith() for local scheme and execute function. 
![Screenshot 2024-01-24 at 2 08 44 PM](https://github.com/nuxt-alt/auth/assets/6570598/76437ae0-90e2-4e90-909e-9b98e1eb0c46)

### Describe the bug

![Screenshot 2024-01-24 at 2 09 21 PM](https://github.com/nuxt-alt/auth/assets/6570598/3866d244-8ac2-471e-87b8-e6bab03efc68)

### Additional context

Tried everything from installing Pinia to adjusting order of Nuxt modules, but nothing worked.

**Comment by Denoder** [comment]
Can you show me what the `Preview` and `Response` is putting out?

**Comment by azmatzuberi** [comment]
Here are the two items you asked for:
![Screenshot 2024-01-24 at 6 51 45 PM](https://github.com/nuxt-alt/auth/assets/6570598/b1c2dcf3-78f7-499e-b9d1-298bbbbc6179)
![Screenshot 2024-01-24 at 6 51 58 PM](https://github.com/nuxt-alt/auth/assets/6570598/93fb3587-ddb4-4c04-95fe-3f4ff7c4ed87)

**Comment by Denoder** [comment]
This leads me to believe that anything under `http://localhost:4500` wont output anything.

**Comment by Denoder** [comment]
are you able to provide a reproducible link for me to test this?

**Comment by azmatzuberi** [comment]
It was my error.
