### ISSUE TITLE
Get client_id from runtime config

### ISSUE THREAD

**Issue by hendrikheil** [nuxt-alt/auth#2]
First off, a huge thank you for putting in the work for making this module available for nuxt3!

I noticed something from trying to use this module in production that is a bit cumbersome to work around. Right now it seems like one can't really define dynamic configuration like a client_id from the runtimeConfig.

Not sure if the generated plugin can be easily adjusted to merge the static strategy configuration with runtimeConfig data?

**Comment by vinayakkulkarni** [comment]
`process.env.CLIENT_ID` ?

**Comment by hendrikheil** [comment]
I think that unfortunately doesn't work for runtime config changes. At buildtime that variable would be replaced with the literal value, so it can't be changed by just updating the environment variables.
