### ISSUE TITLE
Local strategy keeps making backend request without any data

### ISSUE THREAD

**Issue by azmatzuberi** [nuxt-alt/auth#23]
I've set up my local strategy with the correct backend URL and method, but it keeps getting a 400 error while no data was even sent. In the network tab it shows no payload. I've been playing around with this for some time now and can't figure out why this 400 error keeps persisting even though I've passing the username and password using the loginWith function.
<img width="1792" alt="Screenshot 2023-02-02 at 1 41 35 PM" src="https://user-images.githubusercontent.com/6570598/216420123-f6ac6045-1ed8-4e6b-97d3-9f0c00dc7300.png">

**Comment by hendrikheil** [comment]
Are you passing the payload correctly?

Your method call should look like this:
```
    await auth.loginWith('myStrategy', {
      body: {
        email: 'my@e.mail',
        password: 'hunter2',
      },
    });
```
