### ISSUE TITLE
middleware on select pages is not working

### ISSUE THREAD

**Issue by azmatzuberi** [nuxt-alt/auth#29]
Following the original nuxt auth system, I put `middleware: 'auth'` on a page, but I could still navigate to it without being logged on. I then went to the module options and put `enableMiddleware: true` but still no luck.

**Comment by lowbits** [comment]
@azmatzuberi did you add redirects in your config file?
Im using the package and login redirect it working

```ts
//nuxt.config.ts
auth: {
    redirect: {
      login: '/auth/signin',
      callback: '/auth/signin',
    },
}

``

**Comment by steklopod** [comment]
If you use Vue - `middleware: 'auth'` will not work.

**Comment by mcazeneuve** [comment]
with nuxt3 it works
<script lang="ts" setup >
definePageMeta({
  middleware: "auth"
});
</script>
