### ISSUE TITLE
useRuntimeConfig is not defined

### ISSUE THREAD

**Issue by RadBe** [nuxt-alt/auth#30]
I install clean nuxt and nuxt-alt. When run: npm run dev, I get error:
500
useRuntimeConfig is not defined
project/.nuxt/auth.plugin.mjs:48:60

This place in here:
[https://github.com/nuxt-alt/auth/blob/main/src/plugin.ts#L40](https://github.com/nuxt-alt/auth/blob/main/src/plugin.ts#L40)

**Comment by steklopod** [comment]
@RadBe  `useRuntimeConfig` is related ti Nuxt. Not for auth module

**Comment by Xezard** [comment]
The error occurs only when automatic imports are disabled in nuxt itself - because there is no direct import in the module and it crashes. If you enable automatic imports from nuxt - import useRuntimeConfig will resolve automatically.
