### ISSUE TITLE
Redirect doesn't work on login

### ISSUE THREAD

**Issue by mkael1** [nuxt-alt/auth#31]
Version ^2.3.2

On logout it works, but when I try to login it doesn't redirect to /

```
  auth: {
    strategies: {
      laravelSanctum: {
        sessionStorage: true,
        provider: "laravel/sanctum",
        url: process.env.API_URL,
        endpoints: {
          csrf: {
            url: '/sanctum/csrf-cookie',
          },
          login: {
            url: "/api/admin/login"
          },
          user: {
            url: "/api/admin/user"
          },
          logout: {
            url: "/api/admin/logout"
          }
        }
      }
    },
    redirect: {
      login: "/login",
      logout: "/login",
      callback: "/login",
      home: "/"
    }
  },
```

**Comment by betsaleel777** [comment]
same issue for me, there is no example to use this package

**Comment by betsaleel777** [comment]
i resolved redirection issue that way:
`auth: {
    strategies: {
      local: {
        token: {
          property: "token",
          global: true,
        },
        user: {
          property: "user",
          autoFetch: true,
        },
        endpoints: {
          login: { url: "/login", method: "post" },
          logout: { url: "/logout", method: "post" },
          user: { url: "/user", method: "get" },
        },
      },
    },
    globalMiddleware: true,
    watchLoggedIn: true,
    redirectStrategy: "query",
    redirect: {
      login: "login",
      logout: "login",
      home: "/",
    },
  },`
but how define baseURL globally, 
`http: { baseURL: ... },` doesn't work

**Comment by dtobi59** [comment]
I solve this by creating a file in the plugin dir, then wrote the code below:
```

export default defineNuxtPlugin(nuxtApp => {  

    $http.setBaseURL("base_url_here")
    
})
```
