### ISSUE TITLE
Need an example/usage

### ISSUE THREAD

**Issue by duongxinh2003** [nuxt-alt/auth#34]
Thank you for creating this library. Not only I but everyone also wants to see an example of how to use this module.

**Comment by steklopod** [comment]
Also it would be nice ti know how to provide custom user type with TS. I mean override this from lib:

```ruby
user: Record<string, any>
```

To
```kotlin
user: MyUserInterface
```

___
Example of usage: `useAuth().user.email`

**Comment by Teranode** [comment]
I don't have the backend tools necessary to provide ample examples of the login features the module contains.

I've only mainly ported what was available from the official auth module to nuxt 3 with some little tweaks here and there so whatever bugs the module came with before will probably still be in this module, but If people provide PRs I can take a look at them.

@steklopod I'll see to add something for that in a later version.

**Comment by lowbits** [comment]
@Teranode i can provide an example, because i use your package in two of my apps, with an nestjs backend.

**Comment by steklopod** [comment]
@Teranode you can use my api:
```http
### Login
POST https://colaba.online/api/auth/login
Content-Type: application/json

{
"email": "test@colaba.online",
"password": "test"
}
```

There are endpoints:
```js
          login: { url: `https://colaba.online/api/auth/login`, method: 'post' },
          user: { url: `https://colaba.online/api/auth/user`, method: 'post' },
          refresh: { url: `https://colaba.online/api/auth/refresh`, method: 'post' },
          logout: { url: `https://colaba.online/api/auth/logout`, method: 'post' }
```

It also has oAuth2 URL: 
- https://colaba.online/api/auth/auth/oauth2/authorization/google

**Comment by Denoder** [comment]
> Also it would be nice ti know how to provide custom user type with TS. I mean override this from lib:
> 
> ```ruby
> user: Record<string, any>
> ```
> 
> To
> 
> ```kotlin
> user: MyUserInterface
> ```
> 
> Example of usage: `useAuth().user.email`

Ill be adding this in the next version

**Comment by steklopod** [comment]
@Denoder where we could have a look at the example? I did not find it in the readme

**Comment by Denoder** [comment]
@steklopod the readme didn't push through here, i've pushed it: https://github.com/nuxt-alt/auth#typescript-260

**Comment by steklopod** [comment]
I did like this and it works:

```ts
declare module '@nuxt-alt/auth' {
    import type { User } from '~/api/auth/models/user'
    interface UserInfo extends User {    }
}
```

**Comment by Denoder** [comment]
> I did like this :
> 
> ```ts
> declare module '@nuxt-alt/auth' {
>     import type { User } from '~/api/auth/models/user'
>    export interface UserInfo extends User {    }
> }
> ```

@steklopod 
This is how I have my types set up:

```ts
import '@nuxt-alt/auth'

declare module '@nuxt-alt/auth' {
    interface UserInfo {
        email: string
        name: string
        providers: UserProviders[]
        preferences: UserPreferences
    }
}
```
