### ISSUE TITLE
oAuth2 login not working in version 2.3.12

### ISSUE THREAD

**Issue by steklopod** [nuxt-alt/auth#49]
I have my own backend that provides oAuth2 flow. So I am not using oAuth2 functionality from the `nuxt-alt` lib.
In version **2.3.11** I am logged in and have such cookies:
<img width="942" alt="Снимок экрана 2023-04-20 в 13 00 14" src="https://user-images.githubusercontent.com/29500153/233346640-8d72dbb9-8a0c-40c5-91f0-e870b2d5db5a.png">

It seems like `nuxt-alt/auth` duplicates my `.server.cookie` (`server.cookie` without dot in domain column). But it works. 

With version >**2.3.12** (up to the latest) I am not logged in and only `.server.cookie` with dot at the beginning presents
___
I saw that function `getCookies()`  was removed in **2.3.12** https://github.com/nuxt-alt/auth/commit/81c7ae0b2a93d372c65d9fdfe9e33632eaea38f5

<img width="579" alt="Снимок экрана 2023-04-20 в 13 12 04" src="https://user-images.githubusercontent.com/29500153/233349248-db30c47c-753d-4b73-995a-5fa354fa881d.png">

**Comment by Teranode** [comment]
the leading dot notation of the cookie (.colaba.online) would be able to work with the nod dot one (colaba.online) if that's what set in the domain otherwise the duplication is unnecessary.

**Comment by steklopod** [comment]
Thank for the reply. I can prove that removing dot `.` prefix from cookie's domain solved the problem. So oAuth2 works with the latest version `2.4.2` 👍🏻
