### ISSUE TITLE
Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body

### ISSUE THREAD

**Issue by lowbits** [nuxt-alt/auth#50]
Hey @Teranode, after upgrading i cannot add a query Parameter to my loginWith method, before it was possible.

```ts
   await $auth.loginWith('local', {
        query: {token: token.value},
    })
```

I get following error

`ERRR FetchError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body. (http://localhost:8000/api/auth/magiclogin/callback?token=foo`

**Comment by Teranode** [comment]
I'm almost 100% certain logging in make a post request, so im uncertain as to how you're making a get request, there isn't enough information here for me to debug this.

**Comment by lowbits** [comment]
Ah sorry, you can configure it in the object like:


```ts

strategies: {
            local: {
                enabled: true,
                provider: 'laravel/jwt',
                url: process.env.API_BASE_URL,
                endpoints: {
                    login: {
                        url: '/api/auth/magiclogin/callback',
                        method: 'GET',
                    },
                    refresh: {
                        url: '/api/auth/refresh',
                    },
                    logout: {
                        url: '/api/auth/logout',
                    },
                    user: {
                        url: '/api/auth/me',
                    },
                },
                token: {
                    property: 'access_token',
                    maxAge: 60 * 60,
                },
                refreshToken: {
                    maxAge: 20160 * 60,
                },
            },
        },

```

**Comment by Teranode** [comment]
```ts
login: {
    url: '/api/auth/magiclogin/callback',
    method: 'GET',
},
```

the `method: 'GET' ` is the issue, there was an issue before where the body wasn't weren't being included in the local scheme due the acta that the body wasnt preset if someone added a client ide or other params.

https://github.com/nuxt-alt/auth/blob/af9e96a4111140c31d4618165dd11ccf61807c2e/src/runtime/schemes/local.ts#L131

so now it has a empty body by default, and from what I've seen all login requests are POST methods so I don't think using get would be advised.
