### ISSUE TITLE
Skip Global Middleware on Specific Route Using Script Setup

### ISSUE THREAD

**Issue by joshwhitwell** [nuxt-alt/auth#64]
Can you please add instructions to the documentation regarding how to skip the global authorization middleware on a particular route when using script setup syntax?

In Nuxt 2 / Options Api you could skip the global auth middleware on a particular route/component by using:

```
export default {
  auth: false
}
```

Is there a way to accomplish the same thing when using script setup / `useAuth` composable, e.g.

```
<script setup>
const { $auth } = useNuxtApp()
const auth = useAuth()
// How to skip auth here?
```

or somewhere in nuxt.config.ts?

**Comment by Denoder** [comment]
yea I should do that but here:

```vue
<script lang="ts" setup>
definePageMeta({
    auth: false
});
</script>
```
