### ISSUE TITLE
Question: how to protect a server route

### ISSUE THREAD

**Issue by VladBrok** [nuxt-alt/auth#65]
Hello. Could you please tell how can I protect the api route. I've tried to use /server/middleware/auth.ts with defineEventHandler and useAuth, but it's not working

**Comment by Denoder** [comment]
I don't believe there is a way to access the nitro/h3 layer currently. Not sure why nuxt has a nitro server level, a nuxt server level and a nuxt client level. but i'm not looking to rewrite a chunk of the module to accommodate the nitro layer.

You're free to make a PR to change that.

**Comment by VladBrok** [comment]
@Denoder ok, thank you very much for the quick reply
