### ISSUE TITLE
The pinia store is not activated. Only in nuxt 3.7.2

### ISSUE THREAD

**Issue by RadBe** [nuxt-alt/auth#67]
### Environment

Nuxt 3.7.2

### Nuxt Config

modules: [
    '@nuxt-alt/auth',
    '@pinia/nuxt',
  ],

### Reproduction

Just install nuxt and auth latest versions

### Describe the bug

In nuxt 3.7.2 I get this error:
```[AUTH] The pinia store is not activated. This might cause issues in auth module behavior, like redirects not working properly. To activate it, please install it and add it to your config after this module```

But in nuxt 3.7.1 is ok

**Comment by Denoder** [comment]
@RadBe try 3.7.3 and see if that hotfix was the solution.
